name: ci

on:
  push:
  branches:
    - 'main/*'  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: Build image
      name: Check out repository
    - uses: test
      name: Check out repository 
