name: ci

on: push  

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: buidl the image
    steps:
      - name: build the imagep
        id: build
        uses: actions/Dockerfile@v1
        with:
          who-to-greet: 'Mona the Octocat'
